import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';
import { createMcpHandler } from 'mcp-handler';
import { isValidId } from '@/lib/ids';
import { clientIp } from '@/lib/ip';
import { mcpExposedActions } from '@/lib/ir';
import { kv } from '@/lib/kv';
import { getLimiter, tooMany } from '@/lib/ratelimit';
import { safeFetch, SsrfError, UpstreamError } from '@/lib/ssrf';
import { buildUpstreamRequest, UpstreamBuildError } from '@/lib/upstream';
import { validateParams } from '@/lib/validate';

export const maxDuration = 60;

// Multi-tenant MCP server (Streamable HTTP, stateless): the handler is
// constructed per request with the tools resolved from the stored import.
// Tool schemas are the stored JSON Schema verbatim — no zod round-trip —
// and tools/call args are validated with the same Ajv the proxy uses.

function jsonRpcError(status: number, message: string): Response {
  return Response.json(
    { jsonrpc: '2.0', error: { code: -32001, message }, id: null },
    { status },
  );
}

function toolText(text: string, isError = false) {
  return { content: [{ type: 'text' as const, text }], isError };
}

async function handler(req: Request, ctx: { params: Promise<{ id: string }> }) {
  const { id } = await ctx.params;
  if (!isValidId(id)) return jsonRpcError(404, 'Unknown or expired Spotcheck id');

  const rl = await getLimiter('mcp', { limit: 60, windowSec: 60 }).limit(clientIp(req));
  if (!rl.success) return tooMany(rl.reset);

  const record = await kv().getImport(id);
  if (!record || record.expiresAt <= Date.now()) {
    return jsonRpcError(404, 'Unknown or expired Spotcheck id — re-import the spec to mint a new server');
  }

  // BYOK: upstream credential rides a documented header (preferred) or ?key=
  const upstreamKey =
    req.headers.get('x-spotcheck-upstream-key') ??
    new URL(req.url).searchParams.get('key') ??
    undefined;

  const exposed = mcpExposedActions(record);

  const mcp = createMcpHandler(
    (server) => {
      const low = server.server;
      low.setRequestHandler(ListToolsRequestSchema, async () => ({
        tools: exposed.map((a) => ({
          name: a.name,
          description: a.description,
          inputSchema: a.paramsSchema as { type: 'object'; [k: string]: unknown },
          annotations: {
            title: `${a.method} ${a.path}`,
            readOnlyHint: a.safety === 'read',
            destructiveHint: false,
            openWorldHint: true,
          },
        })),
      }));

      low.setRequestHandler(CallToolRequestSchema, async ({ params }) => {
        const action = exposed.find((a) => a.name === params.name);
        if (!action) return toolText(`Unknown tool: ${params.name}`, true);

        const baseUrl = record.baseUrls[0];
        if (!baseUrl) {
          return toolText('This API declared no public base URL — calls are disabled.', true);
        }

        const args = (params.arguments ?? {}) as Record<string, unknown>;
        const invalid = validateParams(action, args);
        if (invalid) return toolText(`Invalid arguments: ${invalid}`, true);

        if (action.auth !== 'none' && !upstreamKey) {
          return toolText(
            `This API requires ${action.auth} auth. Supply your key via the x-spotcheck-upstream-key header (or ?key= in the server URL). Spotcheck never stores it.`,
            true,
          );
        }

        try {
          const upstream = buildUpstreamRequest(action, args, { token: upstreamKey }, baseUrl, record.authIn);
          const res = await safeFetch(upstream.url, {
            method: upstream.method,
            headers: upstream.headers,
            body: upstream.body,
            timeoutMs: 30_000,
            maxBytes: 1024 * 1024,
          });
          console.log('[mcp]', { id, tool: action.name, status: res.status, latencyMs: res.latencyMs });
          const text = new TextDecoder().decode(res.body);
          const summary = `HTTP ${res.status} · ${res.latencyMs}ms\n${text || '(empty body)'}`;
          return toolText(summary, res.status >= 400);
        } catch (err) {
          if (err instanceof UpstreamBuildError) return toolText(err.message, true);
          if (err instanceof SsrfError) return toolText('Upstream URL blocked by safety policy.', true);
          if (err instanceof UpstreamError) return toolText(err.message, true);
          console.error('[mcp] unexpected', { id, tool: action.name });
          return toolText('Tool call failed unexpectedly.', true);
        }
      });
    },
    {
      serverInfo: { name: `spotcheck-${record.id}`, version: '0.1.0' },
      capabilities: { tools: {} },
      instructions: `Tools for the "${record.name}" API, generated by Spotcheck. ${
        record.auth !== 'none'
          ? 'Requests need the caller-supplied upstream API key (BYOK) — it is passed through, never stored.'
          : ''
      }`,
    },
    {
      streamableHttpEndpoint: `/mcp/${id}`,
      disableSse: true,
      maxDuration: 55,
      verboseLogs: false,
    },
  );

  return mcp(req);
}

export { handler as GET, handler as POST, handler as DELETE };
