// generate_contract_test — emit a runnable smoke test for one operation.
//
// This is the tool that turns advice into something a team can put in CI: it
// pins the two things that actually break silently, the status class and the
// documented response fields, so the next spec drift fails a build instead of
// a production agent.
//
// Codegen safety: every value interpolated into the emitted source goes through
// JSON.stringify (or a numeric coercion), so a spec containing quotes,
// newlines, backticks, or `'; rm -rf /` produces an escaped string literal
// rather than executable code. Nothing here shells out or evals — the output is
// text handed back to the caller.

import { buildSampleParts } from '../snippets';
import type { Action, ImportRecord } from '../ir';
import { asData, type AdvisorContext } from './types';

export type ContractTestLanguage = 'typescript' | 'python' | 'bash';

// Top-level documented response fields — what a contract test should assert on.
// Required fields are the strongest signal; absent a `required` list, fall back
// to the declared property names.
function assertableFields(action: Action): string[] {
  const schema = action.responseSchema as
    | { properties?: Record<string, unknown>; required?: unknown; items?: unknown; type?: unknown }
    | undefined;
  if (!schema) return [];

  // Array responses: assert on the item shape instead of the envelope.
  const node =
    schema.type === 'array' || schema.items
      ? ((schema.items ?? {}) as { properties?: Record<string, unknown>; required?: unknown })
      : schema;

  const required = Array.isArray(node.required)
    ? (node.required as unknown[]).filter((r): r is string => typeof r === 'string')
    : [];
  if (required.length) return required.slice(0, 12);
  return node.properties ? Object.keys(node.properties).slice(0, 8) : [];
}

function isArrayResponse(action: Action): boolean {
  const schema = action.responseSchema as { type?: unknown; items?: unknown } | undefined;
  return Boolean(schema && (schema.type === 'array' || schema.items));
}

const KEY_ENV = 'API_KEY';

function tsTest(action: Action, record: ImportRecord): string {
  const base = record.baseUrls[0] ?? 'https://api.example.com';
  const parts = buildSampleParts(action, base, record.authIn ?? action.authIn);
  const fields = assertableFields(action);
  const arrayResponse = isArrayResponse(action);

  const headerEntries = parts.headers.map(([k, v]) =>
    v.includes('$API_KEY')
      ? `    ${JSON.stringify(k)}: \`${v.replace('$API_KEY', '${apiKey}')}\`,`
      : `    ${JSON.stringify(k)}: ${JSON.stringify(v)},`,
  );

  const lines: string[] = [
    `// Contract test for ${action.name} (${action.method} ${action.path})`,
    `// Generated by DocentAPI. Run: node --test ${action.name}.contract.test.ts`,
    `import { test } from 'node:test';`,
    `import assert from 'node:assert/strict';`,
    ``,
    `const apiKey = process.env.${KEY_ENV} ?? '';`,
    ``,
    `test(${JSON.stringify(`${action.name} honours its documented contract`)}, async () => {`,
    `  const res = await fetch(${JSON.stringify(parts.url)}, {`,
    `    method: ${JSON.stringify(action.method)},`,
  ];
  if (headerEntries.length) lines.push(`    headers: {`, ...headerEntries.map((l) => `  ${l}`), `    },`);
  if (parts.body !== undefined) {
    lines.push(`    body: JSON.stringify(${JSON.stringify(parts.body)}),`);
  }
  lines.push(
    `  });`,
    ``,
    `  // 1. Status class: a documented operation must not 4xx/5xx on a valid call.`,
    `  assert.ok(res.ok, \`expected a 2xx, got \${res.status}\`);`,
  );

  if (action.responseSchema) {
    lines.push(
      ``,
      `  // 2. Content type: the spec documents a JSON response body.`,
      `  assert.match(res.headers.get('content-type') ?? '', /json/i);`,
      ``,
      `  const body = await res.json();`,
    );
    if (fields.length) {
      lines.push(
        `  // 3. Documented fields still present — this is the assertion that catches drift.`,
        arrayResponse
          ? `  const sample = Array.isArray(body) ? body[0] : (body?.data ?? body?.items ?? body)?.[0];`
          : `  const sample = body;`,
      );
      if (arrayResponse) {
        lines.push(`  assert.ok(sample !== undefined, 'expected at least one item to inspect');`);
      }
      for (const field of fields) {
        lines.push(
          `  assert.ok(sample?.${/^[A-Za-z_$][\w$]*$/.test(field) ? field : `[${JSON.stringify(field)}]`} !== undefined, ${JSON.stringify(
            `documented field "${field}" is missing from the response`,
          )});`,
        );
      }
    } else {
      lines.push(`  assert.ok(body !== undefined, 'expected a JSON body');`);
    }
  } else {
    lines.push(
      ``,
      `  // The spec documents no response schema for this operation, so there is`,
      `  // nothing to assert beyond the status. Add a response schema upstream to`,
      `  // make this test catch drift.`,
    );
  }

  lines.push(`});`);
  return lines.join('\n');
}

function pyTest(action: Action, record: ImportRecord): string {
  const base = record.baseUrls[0] ?? 'https://api.example.com';
  const parts = buildSampleParts(action, base, record.authIn ?? action.authIn);
  const fields = assertableFields(action);
  const arrayResponse = isArrayResponse(action);

  const headerLines = parts.headers.map(([k, v]) =>
    v.includes('$API_KEY')
      ? `        ${JSON.stringify(k)}: f${JSON.stringify(v.replace('$API_KEY', '{api_key}'))},`
      : `        ${JSON.stringify(k)}: ${JSON.stringify(v)},`,
  );

  const lines: string[] = [
    `# Contract test for ${action.name} (${action.method} ${action.path})`,
    `# Generated by DocentAPI. Run: pytest ${action.name}_contract_test.py`,
    `import os`,
    `import requests`,
    ``,
    `api_key = os.environ.get(${JSON.stringify(KEY_ENV)}, "")`,
    ``,
    `def test_${action.name.replace(/[^\w]/g, '_')}_contract():`,
    `    res = requests.request(`,
    `        ${JSON.stringify(action.method)},`,
    `        ${JSON.stringify(parts.url)},`,
  ];
  if (headerLines.length) lines.push(`        headers={`, ...headerLines.map((l) => `    ${l}`), `        },`);
  if (parts.body !== undefined) lines.push(`        json=${pyLiteral(parts.body)},`);
  lines.push(
    `        timeout=30,`,
    `    )`,
    ``,
    `    # 1. Status class`,
    `    assert res.ok, f"expected a 2xx, got {res.status_code}"`,
  );

  if (action.responseSchema) {
    lines.push(
      ``,
      `    # 2. Content type`,
      `    assert "json" in res.headers.get("content-type", "").lower()`,
      ``,
      `    body = res.json()`,
    );
    if (fields.length) {
      lines.push(
        `    # 3. Documented fields still present`,
        arrayResponse
          ? `    sample = body[0] if isinstance(body, list) else (body.get("data") or body.get("items") or [body])[0]`
          : `    sample = body`,
      );
      for (const field of fields) {
        lines.push(`    assert ${JSON.stringify(field)} in sample, ${JSON.stringify(`documented field "${field}" is missing`)}`);
      }
    } else {
      lines.push(`    assert body is not None`);
    }
  } else {
    lines.push(``, `    # No documented response schema — status is all there is to assert.`);
  }

  return lines.join('\n');
}

function pyLiteral(value: unknown): string {
  return JSON.stringify(value).replace(/\btrue\b/g, 'True').replace(/\bfalse\b/g, 'False').replace(/\bnull\b/g, 'None');
}

function bashTest(action: Action, record: ImportRecord): string {
  const base = record.baseUrls[0] ?? 'https://api.example.com';
  const parts = buildSampleParts(action, base, record.authIn ?? action.authIn);
  const fields = assertableFields(action);

  const lines: string[] = [
    `#!/usr/bin/env bash`,
    `# Contract test for ${action.name} (${action.method} ${action.path})`,
    `# Generated by DocentAPI. Requires curl and jq. Exits non-zero on failure.`,
    `set -euo pipefail`,
    ``,
    `: "\${${KEY_ENV}:=}"`,
    `response=$(mktemp)`,
    `trap 'rm -f "$response"' EXIT`,
    ``,
    `status=$(curl -sS -o "$response" -w '%{http_code}' \\`,
    `  -X ${shq(action.method)} ${shq(parts.url)} \\`,
  ];
  for (const [k, v] of parts.headers) {
    lines.push(`  -H ${shHeader(k, v)} \\`);
  }
  if (parts.body !== undefined) lines.push(`  -d ${shq(JSON.stringify(parts.body))} \\`);
  lines.push(
    `  )`,
    ``,
    `if [[ "$status" -lt 200 || "$status" -ge 300 ]]; then`,
    `  echo "FAIL: expected a 2xx, got $status" >&2`,
    `  cat "$response" >&2`,
    `  exit 1`,
    `fi`,
  );

  if (fields.length) {
    lines.push(
      ``,
      `for field in ${fields.map((f) => shq(f)).join(' ')}; do`,
      `  if ! jq -e --arg f "$field" '(if type == "array" then .[0] else (.data[0]? // .items[0]? // .) end) | has($f)' "$response" >/dev/null; then`,
      `    echo "FAIL: documented field \\"$field\\" is missing from the response" >&2`,
      `    exit 1`,
      `  fi`,
      `done`,
    );
  }
  lines.push(``, `echo "PASS: ${action.name} (HTTP $status)"`);
  return lines.join('\n');
}

// Single-quote shell escaping: the only way a single-quoted string ends is a
// literal quote, so close/escape/reopen is exhaustive.
function shq(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

// A header whose value carries the API_KEY placeholder needs the shell to
// EXPAND that variable — and inside single quotes it never does, so a naively
// escaped header ships the literal text "$API_KEY" to the upstream API. This
// emits '<literal>'"$API_KEY" instead: every literal part stays single-quoted
// (and so uninterpretable by the shell), while the variable sits in double
// quotes where it expands and is still safe against word splitting.
function shHeader(name: string, value: string): string {
  const literal = `${name}: ${value}`;
  if (!literal.includes('$API_KEY')) return shq(literal);
  return literal
    .split('$API_KEY')
    .map((part) => (part ? shq(part) : ''))
    .join(`"$${KEY_ENV}"`);
}

export type ContractTestArgs = { tool?: unknown; language?: unknown };

export function generateContractTest(ctx: AdvisorContext, args: ContractTestArgs) {
  const wanted = typeof args.tool === 'string' ? args.tool.trim() : '';
  if (!wanted) return { error: 'tool is required — pass the tool name returned by search_endpoints.' };

  const action = ctx.record.actions.find((a) => a.name === wanted);
  if (!action) return { error: `No operation named "${asData(wanted, 80)}" exists on this API.` };

  const requested = typeof args.language === 'string' ? args.language.toLowerCase() : 'typescript';
  const language: ContractTestLanguage =
    requested === 'python' ? 'python' : requested === 'bash' || requested === 'curl' ? 'bash' : 'typescript';

  const source =
    language === 'python' ? pyTest(action, ctx.record) : language === 'bash' ? bashTest(action, ctx.record) : tsTest(action, ctx.record);

  const fields = assertableFields(action);
  const drift = ctx.insights.driftObservations.find((o) => o.actionId === action.id);

  return {
    tool: action.name,
    call: `${action.method} ${action.path}`,
    language,
    filename:
      language === 'python'
        ? `${action.name}_contract_test.py`
        : language === 'bash'
          ? `${action.name}.contract.sh`
          : `${action.name}.contract.test.ts`,
    source,
    asserts: {
      statusClass: true,
      contentType: Boolean(action.responseSchema),
      documentedFields: fields,
    },
    ...(action.safety !== 'read'
      ? {
          warning: `This operation is classified "${action.safety}". The generated test performs a real ${action.method}; point it at a sandbox environment before adding it to CI.`,
        }
      : {}),
    ...(fields.length === 0
      ? {
          limitation:
            'The spec documents no response fields for this operation, so the test can only assert the status class. Adding a response schema upstream makes it catch drift.',
        }
      : {}),
    ...(drift
      ? {
          heedsUp: `A verification run already saw ${drift.declaredFields - drift.matchedFields} documented field(s) missing from a real response: ${drift.mismatches.slice(0, 10).join(', ')}. Expect those assertions to fail until the spec or the API is fixed.`,
        }
      : {}),
    setup: `Set ${KEY_ENV} in the environment${action.auth === 'none' ? ' (this operation needs no auth, so it may be left empty)' : ''}. Sample parameter values come from the spec's own examples and may need replacing with real identifiers.`,
  };
}
